#!/usr/bin/env bash
set -ex

# build cli
./node_modules/.bin/esbuild src/generator/cli.ts --bundle --minify --sourcemap --platform=node --target=node16 --outfile=build/cli.js

# run cli (proto to js stuff)
# export PROTO_DIR=src/protos
export PROTO_DIR=$1
# export PROTO_OUT=src/out
export PROTO_OUT=$2
node build/cli.js
